stages:
  preprocess:
    cmd: python preprocess_taxi.py
    deps:
    - data/raw_taxi_data.csv
    - preprocess_taxi.py
    outs:
    - data/cleaned_taxi_data.csv
  train_model:
    cmd: python train_taxi_model.py
    deps:
    - data/cleaned_taxi_data.csv
    - train_taxi_model.py
    outs:
    - taxi_model.pkl
    metrics:
    - taxi_metrics.json:
        cache: false
